apiVersion: apps/v1
kind: Deployment
metadata:
  name: parson-java-one
  labels:
    app: parson-java-one
spec:
  replicas: 2
  selector:
    matchLabels:
      app: parson-java-one
  template:
    metadata:
      labels:
        app: parson-java-one
    spec:
      containers:
      - name: parson-java-one
        image: docker.io/parsontodd/parson-java-one:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5