apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ cookiecutter.artifact_id }}
  namespace: {{ cookiecutter.k8s_namespace }}
  labels:
    app: {{ cookiecutter.artifact_id }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ cookiecutter.artifact_id }}
  template:
    metadata:
      labels:
        app: {{ cookiecutter.artifact_id }}
    spec:
      containers:
        - name: {{ cookiecutter.artifact_id }}
          image: {{ cookiecutter.docker_registry }}/{{ cookiecutter.docker_image_name }}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: JAVA_OPTS
              value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
