apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ cookiecutter.project_slug }}
  labels:
    app: {{ cookiecutter.project_slug }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ cookiecutter.project_slug }}
  template:
    metadata:
      labels:
        app: {{ cookiecutter.project_slug }}
    spec:
      containers:
      - name: {{ cookiecutter.project_slug }}
        image: {{ cookiecutter.docker_registry }}/{{ cookiecutter.docker_image_name }}:${DOCKER_TAG}
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5