# kubernetes/servicemonitor.yml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ cookiecutter.artifact_id }}
  namespace: tools
  labels:
    release: monitoring                  # must match your Helm release name
spec:
  selector:
    matchLabels:
      app: {{ cookiecutter.artifact_id }}  # label on your Service
  namespaceSelector:
    matchNames:
      - {{ cookiecutter.k8s_namespace }}   # your app namespace
  endpoints:
    - port: http                           # matches the Service port name
      path: /actuator/prometheus
      interval: 15s
---
# service exposing /actuator/prometheus specifically (optional, but tidy)
apiVersion: v1
kind: Service
metadata:
  name: {{ cookiecutter.project_slug }}-metrics
  labels:
    app: {{ cookiecutter.project_slug }}
spec:
  selector:
    app: {{ cookiecutter.project_slug }}
  ports:
  - name: metrics
    port: 8081
    targetPort: 8080