apiVersion: v1
kind: Service
metadata:
  name: {{ cookiecutter.project_slug }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ cookiecutter.project_slug }}